-- Get Student Info
SELECT LAST_NAME, FIRST_NAME, GENDER, CITY, TO_CHAR(BIRTH_DATE,'YYYY-MM-DD') as BIRTHDAY from STUDENT WHERE student_ID = 'Z123'

-- Update a student's info
UPDATE STUDENT SET LAST_NAME='Wayne', FIRST_NAME='Bruce', CITY='Ft Lauderdale', GENDER='M', BIRTH_DATE=TO_DATE('1985-07-04', 'YYYY-MM-DD') WHERE STUDENT_ID='Z123'